<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Football Bracket</title>
    <link href="https://fonts.googleapis.com/css?family=Exo+2:400,700&amp;subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="css/main.css">
</head>
<body class="main-body">
    <header>
        <h1>FIFA World Cup 2018</h1>
    </header>

    <main>
        <form action="index.php" method="get">
            <input type="hidden" name="processTournament" value="1">
            <label><input type="checkbox" name="shuffleOnce" <?= isset($_GET['shuffleOnce']) ? ' checked' : '' ?>><span>Жеребьёвка только в 1 этапе</span></label>
            <input type="submit" value="Запустить чемпионат">
        </form>

        <?php if ($bracket->winner != null): ?>
            <h2>Характеристики команд</h2>

            <div class="stat">
                <div class="stat__row stat__row--head">
                    <span class="stat__team-name">Название команды</span>
                    <span class="stat__team-feature">Атака</span>
                    <span class="stat__team-feature">Защита</span>
                </div>

                <?php
                    $maxAttackStr = max(array_column($bracket->stat->teams, 'attackStr'));
                    $maxDefenceStr = max(array_column($bracket->stat->teams, 'defenceStr'));
                ?>
                <?php foreach ($bracket->stat->teams as $teamStat): ?>
                    <div class="stat__row">
                        <span class="stat__team-name"><?= $teamStat['teamName'] ?></span>
                        <span class="stat__team-feature">
                            <?php $attackStrPrc = round($teamStat['attackStr'] * 100 / $maxAttackStr); ?>
                            <span class="stat__team-feature-val" style="width: <?= $attackStrPrc ?>%">
                                <span class="stat__team-feature-numval"><?= $attackStrPrc ?></span>
                            </span>
                        </span>
                        <span class="stat__team-feature">
                            <?php $defenceStrPrc = 100 - round($teamStat['defenceStr'] * 100 / $maxDefenceStr); ?>
                            <span class="stat__team-feature-val" style="width: <?= $defenceStrPrc ?>%">
                                <span class="stat__team-feature-numval"><?= $defenceStrPrc ?></span>
                            </span>
                        </span>
                    </div>
                <?php endforeach; ?>
            </div>

            <h2>Результаты матчей</h2>

            <div class="rounds-wrap">
                <?php foreach ($bracket->rounds as $roundNum => $roundInfo): ?>
                    <div class="round">
                        <?php foreach ($roundInfo['matches'] as $match): ?>
                            <div class="match">
                                <div class="match__team <?= $match->winner == $match->team1 ? 'match__team--winner' : '' ?>">
                                    <span class="match__team-name"><?= $match->team1 ?></span>
                                    <span class="match__team-goals"><?= $match->team1Goals ?></span>
                                </div>
                                <div class="match__team <?= $match->winner == $match->team2 ? 'match__team--winner' : '' ?>">
                                    <span class="match__team-name"><?= $match->team2 ?></span>
                                    <span class="match__team-goals"><?= $match->team2Goals ?></span>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </main>

    <?php if ($bracket->winner != null): ?>
        <footer>
            <h2>Congratulations! The winner is <span class="winner-name"><?= $bracket->winner ?></span></h2>
        </footer>
    <?php endif; ?>
</body>
</html>